// Code generated by kaitai-struct-compiler from a .ksy source file. DO NOT EDIT.

package ksygen

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"io"
)

type DialogueData struct {
	FileSize uint32
	NumEntries int32
	_io *kaitai.Stream
	_root *DialogueData
	_parent interface{}
	_f_entries bool
	entries []*DialogueData_Entry
}
func NewDialogueData() *DialogueData {
	return &DialogueData{
	}
}

func (this *DialogueData) Read(io *kaitai.Stream, parent interface{}, root *DialogueData) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.FileSize = uint32(tmp1)
	tmp2, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.NumEntries = int32(tmp2)
	return err
}
func (this *DialogueData) Entries() (v []*DialogueData_Entry, err error) {
	if (this._f_entries) {
		return this.entries, nil
	}
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	_, err = this._io.Seek(int64((((4 + 4) + (4 * this._root.NumEntries)) + (4 * this._root.NumEntries))), io.SeekStart)
	if err != nil {
		return nil, err
	}
	for i := 0; i < int(this._root.NumEntries); i++ {
		_ = i
		tmp3 := NewDialogueData_Entry()
		err = tmp3.Read(this._io, this, this._root)
		if err != nil {
			return nil, err
		}
		this.entries = append(this.entries, tmp3)
	}
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	this._f_entries = true
	this._f_entries = true
	return this.entries, nil
}
type DialogueData_EntryHeader struct {
	EntryId int32
	AddrtoPostdialogue uint32
	Unk1 int32
	AddrtoPredialogue uint32
	DialogueType int8
	Unk2 int32
	Unk3 int32
	AddrtoAvatar uint32
	AvatarId int32
	DressId int32
	AvatarViceKey int32
	ScreenSide int8
	FaceId int8
	AddrtoFace uint32
	AddrtoFaceAnimation uint32
	AddrtoFaceEffect uint32
	AnimationId int8
	Distortion int8
	Transparency float32
	AddrtoSmth2 uint32
	AddrtoSmth3 uint32
	AddrtoSmth4 uint32
	Unk5 int32
	AddrtoContent uint32
	AddrtoSmth5 uint32
	AddrtoSmth6 uint32
	BackgroundEffect int8
	EnterEffect int8
	AddrtoAudioId uint32
	AudioDelay float32
	AddrtoLipMotion uint32
	Unk7 int8
	AddrtoSmth7 uint32
	AddrtoSmth8 uint32
	AddrtoSmth9 uint32
	AddrtoSmth10 uint32
	Unk8 int32
	Unk9 int32
	AddrtoSmth11 uint32
	AddrtoSmth12 uint32
	AddrtoSmth13 uint32
	_io *kaitai.Stream
	_root *DialogueData
	_parent *DialogueData_Entry
}
func NewDialogueData_EntryHeader() *DialogueData_EntryHeader {
	return &DialogueData_EntryHeader{
	}
}

func (this *DialogueData_EntryHeader) Read(io *kaitai.Stream, parent *DialogueData_Entry, root *DialogueData) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp4, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.EntryId = int32(tmp4)
	tmp5, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.AddrtoPostdialogue = uint32(tmp5)
	tmp6, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.Unk1 = int32(tmp6)
	tmp7, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.AddrtoPredialogue = uint32(tmp7)
	tmp8, err := this._io.ReadS1()
	if err != nil {
		return err
	}
	this.DialogueType = tmp8
	tmp9, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.Unk2 = int32(tmp9)
	tmp10, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.Unk3 = int32(tmp10)
	tmp11, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.AddrtoAvatar = uint32(tmp11)
	tmp12, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.AvatarId = int32(tmp12)
	tmp13, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.DressId = int32(tmp13)
	tmp14, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.AvatarViceKey = int32(tmp14)
	tmp15, err := this._io.ReadS1()
	if err != nil {
		return err
	}
	this.ScreenSide = tmp15
	tmp16, err := this._io.ReadS1()
	if err != nil {
		return err
	}
	this.FaceId = tmp16
	tmp17, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.AddrtoFace = uint32(tmp17)
	tmp18, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.AddrtoFaceAnimation = uint32(tmp18)
	tmp19, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.AddrtoFaceEffect = uint32(tmp19)
	tmp20, err := this._io.ReadS1()
	if err != nil {
		return err
	}
	this.AnimationId = tmp20
	tmp21, err := this._io.ReadS1()
	if err != nil {
		return err
	}
	this.Distortion = tmp21
	tmp22, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.Transparency = float32(tmp22)
	tmp23, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.AddrtoSmth2 = uint32(tmp23)
	tmp24, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.AddrtoSmth3 = uint32(tmp24)
	tmp25, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.AddrtoSmth4 = uint32(tmp25)
	tmp26, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.Unk5 = int32(tmp26)
	tmp27, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.AddrtoContent = uint32(tmp27)
	tmp28, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.AddrtoSmth5 = uint32(tmp28)
	tmp29, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.AddrtoSmth6 = uint32(tmp29)
	tmp30, err := this._io.ReadS1()
	if err != nil {
		return err
	}
	this.BackgroundEffect = tmp30
	tmp31, err := this._io.ReadS1()
	if err != nil {
		return err
	}
	this.EnterEffect = tmp31
	tmp32, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.AddrtoAudioId = uint32(tmp32)
	tmp33, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.AudioDelay = float32(tmp33)
	tmp34, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.AddrtoLipMotion = uint32(tmp34)
	tmp35, err := this._io.ReadS1()
	if err != nil {
		return err
	}
	this.Unk7 = tmp35
	tmp36, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.AddrtoSmth7 = uint32(tmp36)
	tmp37, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.AddrtoSmth8 = uint32(tmp37)
	tmp38, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.AddrtoSmth9 = uint32(tmp38)
	tmp39, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.AddrtoSmth10 = uint32(tmp39)
	tmp40, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.Unk8 = int32(tmp40)
	tmp41, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.Unk9 = int32(tmp41)
	tmp42, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.AddrtoSmth11 = uint32(tmp42)
	tmp43, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.AddrtoSmth12 = uint32(tmp43)
	tmp44, err := this._io.ReadU4le()
	if err != nil {
		return err
	}
	this.AddrtoSmth13 = uint32(tmp44)
	return err
}
type DialogueData_DialogueContent struct {
	NumDialogues int32
	Dialogues []*DialogueData_DialogueEntry
	_io *kaitai.Stream
	_root *DialogueData
	_parent *DialogueData_EntryData
}
func NewDialogueData_DialogueContent() *DialogueData_DialogueContent {
	return &DialogueData_DialogueContent{
	}
}

func (this *DialogueData_DialogueContent) Read(io *kaitai.Stream, parent *DialogueData_EntryData, root *DialogueData) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp45, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.NumDialogues = int32(tmp45)
	for i := 0; i < int(this.NumDialogues); i++ {
		_ = i
		tmp46 := NewDialogueData_DialogueEntry()
		err = tmp46.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Dialogues = append(this.Dialogues, tmp46)
	}
	return err
}
type DialogueData_StrWithLen struct {
	Len uint16
	Value string
	_io *kaitai.Stream
	_root *DialogueData
	_parent interface{}
}
func NewDialogueData_StrWithLen() *DialogueData_StrWithLen {
	return &DialogueData_StrWithLen{
	}
}

func (this *DialogueData_StrWithLen) Read(io *kaitai.Stream, parent interface{}, root *DialogueData) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp47, err := this._io.ReadU2le()
	if err != nil {
		return err
	}
	this.Len = uint16(tmp47)
	tmp48, err := this._io.ReadBytes(int(this.Len))
	if err != nil {
		return err
	}
	tmp48 = tmp48
	this.Value = string(tmp48)
	return err
}
type DialogueData_Entry struct {
	Header *DialogueData_EntryHeader
	Data *DialogueData_EntryData
	_io *kaitai.Stream
	_root *DialogueData
	_parent *DialogueData
}
func NewDialogueData_Entry() *DialogueData_Entry {
	return &DialogueData_Entry{
	}
}

func (this *DialogueData_Entry) Read(io *kaitai.Stream, parent *DialogueData, root *DialogueData) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp49 := NewDialogueData_EntryHeader()
	err = tmp49.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Header = tmp49
	tmp50 := NewDialogueData_EntryData()
	err = tmp50.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Data = tmp50
	return err
}
type DialogueData_StrArr struct {
	NumEntries int32
	Entries []*DialogueData_StrWithLen
	_io *kaitai.Stream
	_root *DialogueData
	_parent *DialogueData_EntryData
}
func NewDialogueData_StrArr() *DialogueData_StrArr {
	return &DialogueData_StrArr{
	}
}

func (this *DialogueData_StrArr) Read(io *kaitai.Stream, parent *DialogueData_EntryData, root *DialogueData) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp51, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.NumEntries = int32(tmp51)
	for i := 0; i < int(this.NumEntries); i++ {
		_ = i
		tmp52 := NewDialogueData_StrWithLen()
		err = tmp52.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.Entries = append(this.Entries, tmp52)
	}
	return err
}
type DialogueData_EntryData struct {
	PostDialogue *DialogueData_U4Arr
	PreDialogue *DialogueData_U4Arr
	Avatar *DialogueData_StrWithLen
	Face *DialogueData_StrWithLen
	FaceAnimation *DialogueData_StrWithLen
	FaceEffect *DialogueData_StrWithLen
	Unknown6 *DialogueData_StrWithLen
	Unknown7 *DialogueData_StrArr
	Unknown8 *DialogueData_StrWithLen
	Content *DialogueData_DialogueContent
	Unknown9 *DialogueData_StrWithLen
	Unknown10 *DialogueData_StrWithLen
	AudioId *DialogueData_StrWithLen
	LipMotion *DialogueData_StrWithLen
	Unknown11 *DialogueData_StrWithLen
	Unknown12 *DialogueData_StrWithLen
	Unknown13 *DialogueData_StrArr
	Unknown14 *DialogueData_StrArr
	Unknown15 *DialogueData_U4Arr
	Unknown16 *DialogueData_StrWithLen
	Unknown17 *DialogueData_StrWithLen
	_io *kaitai.Stream
	_root *DialogueData
	_parent *DialogueData_Entry
}
func NewDialogueData_EntryData() *DialogueData_EntryData {
	return &DialogueData_EntryData{
	}
}

func (this *DialogueData_EntryData) Read(io *kaitai.Stream, parent *DialogueData_Entry, root *DialogueData) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp53 := NewDialogueData_U4Arr()
	err = tmp53.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.PostDialogue = tmp53
	tmp54 := NewDialogueData_U4Arr()
	err = tmp54.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.PreDialogue = tmp54
	tmp55 := NewDialogueData_StrWithLen()
	err = tmp55.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Avatar = tmp55
	tmp56 := NewDialogueData_StrWithLen()
	err = tmp56.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Face = tmp56
	tmp57 := NewDialogueData_StrWithLen()
	err = tmp57.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.FaceAnimation = tmp57
	tmp58 := NewDialogueData_StrWithLen()
	err = tmp58.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.FaceEffect = tmp58
	tmp59 := NewDialogueData_StrWithLen()
	err = tmp59.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Unknown6 = tmp59
	tmp60 := NewDialogueData_StrArr()
	err = tmp60.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Unknown7 = tmp60
	tmp61 := NewDialogueData_StrWithLen()
	err = tmp61.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Unknown8 = tmp61
	tmp62 := NewDialogueData_DialogueContent()
	err = tmp62.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Content = tmp62
	tmp63 := NewDialogueData_StrWithLen()
	err = tmp63.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Unknown9 = tmp63
	tmp64 := NewDialogueData_StrWithLen()
	err = tmp64.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Unknown10 = tmp64
	tmp65 := NewDialogueData_StrWithLen()
	err = tmp65.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.AudioId = tmp65
	tmp66 := NewDialogueData_StrWithLen()
	err = tmp66.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.LipMotion = tmp66
	tmp67 := NewDialogueData_StrWithLen()
	err = tmp67.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Unknown11 = tmp67
	tmp68 := NewDialogueData_StrWithLen()
	err = tmp68.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Unknown12 = tmp68
	tmp69 := NewDialogueData_StrArr()
	err = tmp69.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Unknown13 = tmp69
	tmp70 := NewDialogueData_StrArr()
	err = tmp70.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Unknown14 = tmp70
	tmp71 := NewDialogueData_U4Arr()
	err = tmp71.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Unknown15 = tmp71
	tmp72 := NewDialogueData_StrWithLen()
	err = tmp72.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Unknown16 = tmp72
	tmp73 := NewDialogueData_StrWithLen()
	err = tmp73.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Unknown17 = tmp73
	return err
}
type DialogueData_U4Arr struct {
	NumEntries int32
	Entries []uint32
	_io *kaitai.Stream
	_root *DialogueData
	_parent *DialogueData_EntryData
}
func NewDialogueData_U4Arr() *DialogueData_U4Arr {
	return &DialogueData_U4Arr{
	}
}

func (this *DialogueData_U4Arr) Read(io *kaitai.Stream, parent *DialogueData_EntryData, root *DialogueData) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp74, err := this._io.ReadS4le()
	if err != nil {
		return err
	}
	this.NumEntries = int32(tmp74)
	for i := 0; i < int(this.NumEntries); i++ {
		_ = i
		tmp75, err := this._io.ReadU4le()
		if err != nil {
			return err
		}
		this.Entries = append(this.Entries, tmp75)
	}
	return err
}
type DialogueData_DialogueEntry struct {
	Len int16
	Value string
	Duration float32
	_io *kaitai.Stream
	_root *DialogueData
	_parent *DialogueData_DialogueContent
}
func NewDialogueData_DialogueEntry() *DialogueData_DialogueEntry {
	return &DialogueData_DialogueEntry{
	}
}

func (this *DialogueData_DialogueEntry) Read(io *kaitai.Stream, parent *DialogueData_DialogueContent, root *DialogueData) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp76, err := this._io.ReadS2le()
	if err != nil {
		return err
	}
	this.Len = int16(tmp76)
	tmp77, err := this._io.ReadBytes(int(this.Len))
	if err != nil {
		return err
	}
	tmp77 = tmp77
	this.Value = string(tmp77)
	tmp78, err := this._io.ReadF4le()
	if err != nil {
		return err
	}
	this.Duration = float32(tmp78)
	return err
}
